CREATE PROCEDURE [config].[GetCitiesToLoad]
AS
BEGIN
	SET XACT_ABORT, NOCOUNT ON
	BEGIN TRY
			SELECT City
			FROM config.EtlCities	
	END TRY
	BEGIN CATCH
		IF @@trancount > 0 ROLLBACK TRANSACTION;
		THROW
		RETURN 99999
	END CATCH
END